<?xml version="1.0"?>
<package format="3">
  <name>mechelangelo_imu_driver</name>
  <version>0.0.1</version>
  <description>MECHelangelo Sense HAT IMU driver</description>

  <maintainer email="andrewcoorey13@gmail.com">Andy</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>python3-numpy</depend>
  <depend>python3-pillow</depend>
  <depend>ament_index_python</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
